sequenceDiagram
    autonumber
    participant U as Usuario (Angular)
    participant GW as gateway :8080
    participant AU as users :8081
    participant SU as surveys :8082

    U->>GW: POST /api/auth/login (username, password)
    GW->>AU: forward POST /api/auth/login
    AU-->>GW: 200 { token JWT (userId, roles) }
    GW-->>U: 200 { token JWT }
    Note over U: El interceptor guarda el token<br/>y lo añade a cada petición

    U->>GW: POST /api/surveys (Bearer JWT)
    GW->>SU: forward (Authorization: Bearer ...)
    SU->>SU: Valida JWT (Resource Server, misma clave HMAC)
    SU-->>GW: 201 Encuesta creada
    GW-->>U: 201 Encuesta creada
